branches:
  except:
    - '/@\d+\.\d+\.\d+$/'

language: node_js
node_js:
  - "6"
cache:
  yarn: true
dist: trusty
sudo: false

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: qlNfmz6hBOGFXUvoEAC5lBRly26XGeYe9gBln9RtLGWDY77LzPVCHZu5Ts61Yc3I4UGAHcO4YeaX3rNITclVf/gqV5OOx6JqGykWhfVDVpT1aRupxBmKBVHeeKki9Zu8PDbmpCIVRW6C33BfkI+baeq2nOBEfeYAwFthG1zFZpfjAoVdW2UPn0iww4JhUO74qPtmt7p7+F7cIyTkkfYYajFbBy1/2dlxyNDWJiF9mBrQNs7kiIV8qyM9l/JKYoYaapvJfFCkFhfCI0aAzWoYYt6RlgxY/0yM9zIkOM4R2GPEZEMZVpFfQWFEp4vOOu5YZu0OH1qXbLcLmuT3A0ltx+K7Y1aFsayvl3OkaTsU2zj6kqFaw4o2eOdhcFdSHCOUA0/vRwmqoekAgukg/WRJWORm8bCmJ4Hmd7lscTm7TdU8A6t/hAX85szimHleJNOAza0glZwhlbBcE0/F8Uy19z8HdmaNUoQSg5vh0lBebezFVdMs4BZr7Z1DK4kd8NPrNGhCb56etllWQIKhFRJRHIs+XfeS4cs464JU6z5z023YltQAEoLtggVnGTQK0hAFKZtkRCAtu5bjjPd/o4om+V1ke/q35wLhkaINceY9lBEfusE6o9enXnS9SyxWSgV2y3FofoTwJiOdv8POnyPk6+fN+6EpReircc4minbg2Ng=

addons:
  apt:
    packages:
      - google-chrome-stable

env:
  global:
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome

before_script:
  # For Git
  - git config --global user.email "3846masahiro+git@gmail.com"
  - git config --global user.name "3846masa"
  - git config --global push.default simple
  - git remote set-url origin "https://${GH_USERNAME}:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - git fetch origin $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH

  # Update npm
  - npm i -g npm
  - npm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
  - npm whoami

  # Lerna bootstrap
  - yarn run bootstrap

  # For Chrome
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run test
  - yarn run report
  - yarn run build

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; fi
