language: node_js
node_js:
  - "6"
cache:
  yarn: true
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

env:
  global:
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run test
  - yarn run report
